[toolchain]
channel = "stable"
components = ["clippy", "rust-src", "rustfmt"]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
]
